environment:
  requirementsFile: "requirements-travis.txt"
  matrix:
    - PYTHON: "C:\\Python26"
      requirementsFile: "requirements-travis-26.txt"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - powershell tools\get-packer.ps1

build: off