environment:
  requirementsFile: "requirements-travis.txt"
  matrix:
    - PYTHON: "C:\\Python26"
      requirementsFile: "requirements-travis-26.txt"

install:
  - powershell tools\get-packer.ps1

build: off